### ISSUE TITLE
Failling sampling with adaptive samplers and Categorical parameters

### ISSUE THREAD

**Issue by corentinbeaulieu** [MLCGO/MLKAPS#1]
The sampling step fails while using HVS or GA-Adaptive sampler with Categorical parameters

### Steps to reproduce
- Launch an experiment with `hvs` or `ga_adaptive` sampler using parameters of type "Categorical"
- Error arises after bootstrap when the lightgbm model is trained

### Error messages
In the following `icntl_13`, `ordering` and `par` are defined as Categorical design parameters and `symmetry` is  defined as a Categorical kernel input.

<details>
<summary>
Traceback of an HVS sampled experiment
</summary>

```
Traceback (most recent call last):
  File "bin/mlkaps", line 10, in <module>
    sys.exit(MLKaps.run_from_args())
             ^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/MLKaps.py", line 341, in run_from_args
    run_pipeline(args, config_dict, experiment_config)
  File "mlkaps/MLKaps.py", line 212, in run_pipeline
    kernel_sampling_results = run_kernel_sampling(
                              ^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/MLKaps.py", line 169, in run_kernel_sampling
    df = sample_kernel(experiment_config, config_dict)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/sample_collection/kernel_sampling.py", line 437, in sample_kernel
    res = sampler()
          ^^^^^^^^^
  File "mlkaps/sample_collection/kernel_sampling.py", line 231, in __call__
    samples = orchestrator.run()
              ^^^^^^^^^^^^^^^^^^
  File "mlkaps/sampling/adaptive/orchestrator.py", line 643, in run
    dataset = self._sample()
              ^^^^^^^^^^^^^^
  File "mlkaps/sampling/adaptive/orchestrator.py", line 697, in _sample
    current_error = self.error_evaluator(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/sampling/adaptive/orchestrator.py", line 509, in default_error_evaluator
    model.fit(samples[features], samples[objective])
  File "lightgbm/sklearn.py", line 1189, in fit
    super().fit(
  File "lightgbm/sklearn.py", line 955, in fit
    self._Booster = train(
                    ^^^^^^
  File "lightgbm/engine.py", line 282, in train
    booster = Booster(params=params, train_set=train_set)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lightgbm/basic.py", line 3637, in __init__
    train_set.construct()
  File "lightgbm/basic.py", line 2576, in construct
    self._lazy_init(
  File "lightgbm/basic.py", line 2106, in _lazy_init
    data, feature_name, categorical_feature, self.pandas_categorical = _data_from_pandas(
                                                                       ^^^^^^^^^^^^^^^^^^
  File "lightgbm/basic.py", line 848, in _data_from_pandas
    _pandas_to_numpy(data, target_dtype=target_dtype),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lightgbm/basic.py", line 794, in _pandas_to_numpy
    _check_for_bad_pandas_dtypes(data.dtypes)
  File "lightgbm/basic.py", line 784, in _check_for_bad_pandas_dtypes
    raise ValueError(
ValueError: pandas dtypes must be int, float or bool.
Fields with bad pandas dtypes: par: object, icntl_13: object, ordering: object, symmetry: object
```

</details>

<details>
<summary>
Here is the traceback of a GA-Adaptive based experiment
</summary>

```
Traceback (most recent call last):
  File "mlkaps/sampling/adaptive/ga_adaptive.py", line 177, in __call__
    samples = self._resampling_loop(samples, pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/sampling/adaptive/ga_adaptive.py", line 225, in _resampling_loop
    new_points = self._pick_ga_points(samples, n_ga_points)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/sampling/adaptive/ga_adaptive.py", line 325, in _pick_ga_points
    models = self._fit_models(samples)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/sampling/adaptive/ga_adaptive.py", line 463, in _fit_models
    self.models[obj].fit(
  File "mlkaps/modeling/model_wrapper.py", line 55, in fit
    self._fit(X, y)
  File "mlkaps/modeling/lightgbm_wrapper.py", line 52, in _fit
    self.model.fit(X[self.ordering], y)
  File "lightgbm/sklearn.py", line 1189, in fit
    super().fit(
  File "lightgbm/sklearn.py", line 955, in fit
    self._Booster = train(
                    ^^^^^^
  File "lightgbm/engine.py", line 282, in train
    booster = Booster(params=params, train_set=train_set)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lightgbm/basic.py", line 3637, in __init__
    train_set.construct()
  File "lightgbm/basic.py", line 2576, in construct
    self._lazy_init(
  File "lightgbm/basic.py", line 2106, in _lazy_init
    data, feature_name, categorical_feature, self.pandas_categorical = _data_from_pandas(
                                                                       ^^^^^^^^^^^^^^^^^^
  File "lightgbm/basic.py", line 848, in _data_from_pandas
    _pandas_to_numpy(data, target_dtype=target_dtype),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lightgbm/basic.py", line 794, in _pandas_to_numpy
    _check_for_bad_pandas_dtypes(data.dtypes)
  File "lightgbm/basic.py", line 784, in _check_for_bad_pandas_dtypes
    raise ValueError(
ValueError: pandas dtypes must be int, float or bool.
Fields with bad pandas dtypes: icntl_13: object, ordering: object, par: object, symmetry: object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/mlkaps", line 10, in <module>
    sys.exit(MLKaps.run_from_args())
             ^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/MLKaps.py", line 341, in run_from_args
    run_pipeline(args, config_dict, experiment_config)
  File "mlkaps/MLKaps.py", line 212, in run_pipeline
    kernel_sampling_results = run_kernel_sampling(
                              ^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/MLKaps.py", line 169, in run_kernel_sampling
    df = sample_kernel(experiment_config, config_dict)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "mlkaps/sample_collection/kernel_sampling.py", line 437, in sample_kernel
    res = sampler()
          ^^^^^^^^^
  File "mlkaps/sample_collection/kernel_sampling.py", line 143, in __call__
    res = sampler()
          ^^^^^^^^^
  File "mlkaps/sampling/adaptive/ga_adaptive.py", line 181, in __call__
    raise SamplerError("GA-Adaptive sampling failed!") from exc
mlkaps.sampling.sampler.SamplerError: GA-Adaptive sampling failed!
```

</details>

### Additional information

The origin of the issue identified as a mapping issue of the Categorical parameters can be confirmed thanks to the following patch.
It resolves the HVS case issue by mapping the samples to numeric values before the call to lightgbm.

<details>
<summary>
HVS patch
</summary>

```diff
diff --git a/mlkaps/sampling/adaptive/orchestrator.py b/mlkaps/sampling/adaptive/orchestrator.py
index ce0914b..734487e 100644
--- a/mlkaps/sampling/adaptive/orchestrator.py
+++ b/mlkaps/sampling/adaptive/orchestrator.py
@@ -694,8 +694,9 @@ class AdaptiveSamplingOrchestrator:
                     ]
 
                 # Evaluate the error for each objective
+                encoded_df = self.adaptive_sampler._maybe_map_variables(dataset)
                 current_error = self.error_evaluator(
-                    dataset, list(self.features.keys()), self.objectives
+                    encoded_df, list(self.features.keys()), self.objectives
                 )
```

</details>

**Comment by titeup** [comment]
Hi, I solved this problem in my latest PR #2 
This was a bug when droping column to build the new dataframe X and y to refit the trees.
Types were erased. int and float was dealt automatically, but categorical needed explicit mapping.
